# site settings
title: Titel oder Name
subtitle: Untertitel
email: casdasdasdasd@gmail.com
description: Beschreibung
baseurl: "portfolio" # the subpath of your site, e.g. /blog
url: 'https://s4lbrecht.github.io' # the base hostname & protocol for your site
author:
street_address:
city: Paris
state: Ile-de-France
zip_code: 75
country: France
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: 
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
