# site settings
title: acco{lab}
subtitle: Gestographie
email: contact.accolab@gmail.com
description: Pour un musée participatif de notre culture gestuelle
baseurl: "gestographie" # the subpath of your site, e.g. /blog
url: 'https://accolab.github.io' # the base hostname & protocol for your site
author:
street_address:
city: Paris
state: Ile-de-France
zip_code: 75
country: France
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url: https://www.facebook.com/accolab
github_url: https://github.com/ACCOLAB
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/studio_accolab

# build settings
markdown: kramdown

sass:
  style: compressed
